site_name: "Kaelyn Melton"
site_url:
theme:
  name: material
  logo: img/106997720.jfif
  features: 
    - navigation.instant
    - navigation.tabs
markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
